---
- name: Create the keystore if it doesn't exist yet
  ansible.builtin.command: >
    /usr/share/elasticsearch/bin/elasticsearch-keystore create
  args:
    creates: /etc/elasticsearch/elasticsearch.keystore

- name: Check if bootstrap password is set
  ansible.builtin.command: >
    /usr/share/elasticsearch/bin/elasticsearch-keystore list
  register: _es_keystore
  changed_when: false

- name: Create Bootstrap password for elastic user
  ansible.builtin.shell: set -o pipefail && echo "{{ es_api_basic_auth_password }}" | /usr/share/elasticsearch/bin/elasticsearch-keystore add -x 'bootstrap.password'
  when:
    - _es_keystore is defined
    - ('bootstrap.password' not in _es_keystore.stdout_lines)
  no_log: true
  register: _es_keystore_elastic

- name: Add keystore entries
  ansible.builtin.shell: set -o pipefail && echo "{{ item.value }}" | /usr/share/elasticsearch/bin/elasticsearch-keystore add -x -f {{ item.key }}
  loop: "{{ es_keystore_entries }}"
  loop_control:
    label: "{{ item.key }}"
  when: item.key not in _es_keystore.stdout_lines
  register: _es_keystore_entries

- name: Restart and wait for ElasticSearch
  block:
    - name: Restart ElasticSearch for keystore entries to be taken into account
      ansible.builtin.service:
        name: elasticsearch
        state: restarted

    - name: Wait for ElasticSearch to be running
      ansible.builtin.wait_for:
        host: localhost
        port: "{{ es_http_port }}"

  when: _es_keystore_elastic is changed or _es_keystore_entries is changed
