---
- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ es_dependencies }}"
    state: present
    update_cache: true

- name: Configure Elastic APT repository
  ansible.builtin.deb822_repository:
    components: main
    name: elastic
    signed_by: "{{ es_apt_signed_by }}"
    suites: stable
    uris: "{{ es_apt_uris }}"

- name: Install ElasticSearch
  ansible.builtin.apt:
    name: "{{ es_package_name }}"
    state: "{{ es_package_state }}"
    update_cache: true
  register: _es_apt_package
  notify: Restart ElasticSearch

- name: Ensure ElasticSearch data directory exists
  ansible.builtin.file:
    group: "{{ es_group }}"
    mode: "0755"
    owner: "{{ es_user }}"
    path: "{{ es_path_data }}"
    state: directory

- name: Ensure ElasticSearch log directory exists
  ansible.builtin.file:
    group: root
    mode: "0755"
    owner: "{{ es_user }}"
    path: "{{ es_path_logs }}"
    state: directory

- name: Ensure ElasticSearch configuration files exist
  ansible.builtin.template:
    dest: "/etc/elasticsearch/{{ item | basename | replace('.j2', '') }}"
    group: root
    mode: "0644"
    owner: root
    src: "{{ item }}"
  loop:
    - elasticsearch.yml.j2
    - "{{ es_log4j2_template }}"
    - jvm.options.j2
  notify: Restart ElasticSearch

- name: Include tasks related to plugins
  ansible.builtin.include_tasks: plugins.yml

- name: Ensure ElasticSearch is started and starts at boot
  ansible.builtin.service:
    enabled: true
    name: elasticsearch
    state: started

- name: Wait for ElasticSearch to be running
  ansible.builtin.wait_for:
    host: localhost
    port: "{{ es_http_port }}"

- name: Include tasks related to keystore
  ansible.builtin.include_tasks: keystore.yml

- name: Include tasks related to users
  ansible.builtin.include_tasks: users.yml

- name: Include tasks related to snapshot repositories
  ansible.builtin.include_tasks: snapshot_repositories.yml

- name: Include tasks related to templates
  ansible.builtin.include_tasks: templates.yml

- name: Include tasks related to indices
  ansible.builtin.include_tasks: indices.yml
