---
- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ es_dependencies }}"
    state: present
    update_cache: true

- name: Add Elastic key
  ansible.builtin.apt_key:
    state: present
    url: "{{ es_signing_key }}"

- name: Manage ElasticSearch APT repository
  ansible.builtin.apt_repository:
    repo: "{{ es_repository }}"
    state: present

- name: Install ElasticSearch
  ansible.builtin.apt:
    name: "{{ es_package_name }}"
    state: "{{ es_package_state }}"
  register: _es_apt_package
  notify: Restart ElasticSearch

- name: Ensure ElasticSearch data directory exists
  ansible.builtin.file:
    group: "{{ es_group }}"
    mode: 0755
    owner: "{{ es_user }}"
    path: "{{ es_path_data }}"
    state: directory

- name: Ensure ElasticSearch log directory exists
  ansible.builtin.file:
    group: root
    mode: 0755
    owner: "{{ es_user }}"
    path: "{{ es_path_logs }}"
    state: directory

- name: Ensure ElasticSearch configuration files exist
  ansible.builtin.template:
    dest: "/etc/elasticsearch/{{ item | basename | replace('.j2', '') }}"
    group: root
    mode: 0644
    owner: root
    src: "{{ item }}"
  loop:
    - elasticsearch.yml.j2
    - "{{ es_log4j2_template }}"
    - jvm.options.j2
  notify: Restart ElasticSearch

- include_tasks: plugins.yml

- name: Ensure ElasticSearch is started and starts at boot
  ansible.builtin.service:
    enabled: true
    name: elasticsearch
    state: started

- name: Wait for ElasticSearch to be running
  ansible.builtin.wait_for:
    host: localhost
    port: "{{ es_http_port }}"


- include_tasks: keystore.yml

- include_tasks: users.yml

- include_tasks: snapshot_repositories.yml

- include_tasks: templates.yml

- include_tasks: indices.yml
