---
- name: Prepare
  hosts: all

  tasks:
    - name: Install OpenJDK JRE
      ansible.builtin.apt:
        name: default-jre-headless
        state: present
        update_cache: true

    - name: Install curl (used in tests)
      ansible.builtin.apt:
        name: curl
        state: present
        update_cache: true
